[build]
target = "riscv32imc-unknown-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",
]

[env]
DEFMT_LOG = "info"

[unstable]
build-std = ["core"]
